apiVersion: apps/v1
kind: Deployment
metadata:
  name: async-ai-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: async-ai-consumer
  template:
    metadata:
      labels:
        app: async-ai-consumer
    spec:
      containers:
        - name: async-ai-consumer
          image: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/async-ai-consumer:latest
          env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: S3_BUCKET
              value: "async-ai-inference"
            - name: SQS_QUEUE_URL
              value: "https://sqs.us-east-1.amazonaws.com/314226641988/async-ai-inference-queue"
